version: '3.8'

services:
  apacheserver:
    container_name: apacheServer
    image: httpd
    volumes:
      - ./init/:/usr/local/apache2/htdocs/
    ports:
      - 8086:80
    networks:
      - meuNetwork
networks:
  meuNetwork: {}